# Generated by Django 5.2.9 on 2026-01-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
