# Generated by Django 5.2.9 on 2026-01-04 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_smstemplate_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='scheduled_time',
        ),
    ]
